### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by thasmo** [foray1010/image-process-loader#28]
Is it possible to use `image-process-loader` to generate multiple output files from a single input file? Specifically, can I create multiple differently sized images from a single source image using `image-process-loader`?

**Comment by foray1010** [comment]
@thasmo you can do this in version `1.1.0` by using inline query

example:

```js
import icon32 from '!file-loader?name=images/[name]32.[ext]!image-process-loader?resize=32!../../../img/icon.png'
import icon64 from '!file-loader?name=images/[name]64.[ext]!image-process-loader?resize=64!../../../img/icon.png'
```

the trick is to use file-loader to avoid outputting files with the same name, which will override the previous one
